name: aris_map
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+13

environment:
  sdk: ">=2.10.0-116.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  geolocator: ^6.2.0
  http: ^0.12.2
  google_maps_flutter: ^1.2.0
  firebase_core: ^0.7.0
  firebase_auth: ^0.20.1
  apple_maps_flutter: ^1.0.1
  flutter_push_notifications: ^0.0.2
  flutter_local_notifications: ^4.0.1+2
  provider: ^6.0.1
  flutter_bloc: ^8.0.0
  intl: ^0.16.1
  hive: ^2.0.4
  equatable: ^2.0.3
  get_storage: ^1.4.0
  shared_preferences: ^0.5.12+4
  google_fonts: ^1.1.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
   - assets/splash.png
